### ISSUE TITLE
Incompatible with Go 1.23, which doesn't allow //go:linkname to internal symbols, including to runtime package

### ISSUE THREAD

**Issue by stefanb** [pgavlin/text#1]
While testing Go 1.23 rc1 in 
* https://github.com/Homebrew/homebrew-core/pull/175310
 
there was an error:
````
go install -ldflags '-X github.com/pulumi/pulumi/pkg/v3/version.Version=v3.120.0' github.com/pulumi/pulumi/pkg/v3/cmd/pulumi
# github.com/pulumi/pulumi/pkg/v3/cmd/pulumi
link: github.com/pgavlin/text/internal/bytealg: invalid reference to internal/bytealg.MaxLen
````

Go 1.23 no longer allows `//go:linkname * runtime.*` link instructioins, see 
* https://tip.golang.org/doc/go1.23#linker
* https://github.com/golang/go/issues/67401

It is used several times in this module, see:

https://github.com/search?q=repo%3Apgavlin%2Ftext%20linkname&type=code

**Comment by pgavlin** [comment]
Well, this is unfortunate. Thanks for pointing this out. I'll have to look into what to do here.

**Comment by pgavlin** [comment]
Yeah this is going to take some work to fix.

The only feasible option I see is to vendor in the contents of `internal/bytealg` from the runtime. That will require some edits to the assembly versions of some functions, as they all use the runtime-internal ABI, which is disallowed outside of the runtime.

As a short-term workaround, this package can be used with go1.23 by adding `-checklinkname=0` to `-ldflags` when building.

**Comment by pgavlin** [comment]
Fixed by https://github.com/pgavlin/text/commit/b51d0990e284ec4df4cdce4be716bbfde10b12c1.
